### ISSUE TITLE
Empty value in gene/hpo

### ISSUE THREAD

**Issue by YuanTian1991** [phenopolis/phenopolis_browser#163]
See below front-end issue

https://github.com/phenopolis/phenopolis_frontend_react/issues/219

The issue is caused in code like below:
https://github.com/phenopolis/phenopolis_api/blob/ac9e39893564463d39be7ae78071b7f041ddb2b5/views/individual.py#L198-L199

When there is no gene/hpo in the string, a '"" will be returned. I fixed one in meta data, but not all.

**Comment by pontikos** [comment]
I believe @alanwilter has fixed this.

**Comment by alanwilter** [comment]
yes, it was fixed.
