### ISSUE TITLE
Unique non-empty Key Column in Database

### ISSUE THREAD

**Issue by YuanTian1991** [phenopolis/phenopolis_browser#168]
Please modify the database schema, at least add some unique column and "required" column into each table.

For example, in the Individual table, the key column should be `external_ID`, but I tried that if I don't add below code, I can create patient with same external ID multiple times.

https://github.com/phenopolis/phenopolis_api/blob/3f78ea2ffd6da648dce2e56d46172be154f944e6/views/individual.py#L132-L140

Then, in `_update_individual` function, `external_id` is the only validation, which means, if multiple patients has the same `external_id`, but different `internal_id`, whenever I update one of them all others will be updated...
https://github.com/phenopolis/phenopolis_api/blob/3f78ea2ffd6da648dce2e56d46172be154f944e6/views/individual.py#L359

So, I hope at least we should set key required unique ID for each table.

---

About the required column, take `Individual` table as an example, below code only works when all these columns are at least a string, so it can not be `null`. It means, if someone post a "null" value in `simplified_observed_features_names` to create individual, the create function works, but the patient page can't be opened.
https://github.com/phenopolis/phenopolis_api/blob/3f78ea2ffd6da648dce2e56d46172be154f944e6/views/individual.py#L267-L274

There are a couple solutions for this:
1. We stick current way, I will make sure the front-end will never post null to the backend. (Implemented)
2. Modify the database table schema, make sure no record could be inserted if these value are not string. (Recommanded)
3. Modify above code, to allow null data could go through.

**Comment by pontikos** [comment]
@dvarrazzo is this constraint already implemented?

**Comment by alanwilter** [comment]
This is long done in the new schema:
```sql
phenopolis_db=> \d phenopolis.individual
                              Table "phenopolis.individual"
    Column     |  Type   | Collation | Nullable |                Default
---------------+---------+-----------+----------+----------------------------------------
 id            | integer |           | not null | nextval('individual_id_seq'::regclass)
 phenopolis_id | text    |           | not null |
 external_id   | text    |           |          |
 sex           | text    |           | not null |
 consanguinity | text    |           |          |
Indexes:
    "individual_pkey" PRIMARY KEY, btree (id)
    "individual_external_id_idx" btree (external_id)
    "individual_external_id_key" UNIQUE CONSTRAINT, btree (external_id) <<<------ OK
    "individual_phenopolis_id_idx" btree (phenopolis_id)
    "individual_phenopolis_id_key" UNIQUE CONSTRAINT, btree (phenopolis_id)
Check constraints:
    "ids_match" CHECK (id = replace(phenopolis_id, 'PH'::text, ''::text)::integer)
    "individual_consanguinity_check" CHECK (consanguinity = ANY (ARRAY['yes'::text, 'no'::text, 'unknown'::text]))
    "individual_phenopolis_id_check" CHECK (phenopolis_id ~ '^PH\d+$'::text)
    "individual_sex_check" CHECK (sex = ANY (ARRAY['M'::text, 'F'::text, 'N'::text, 'U'::text]))
Referenced by:
    TABLE "individual_feature" CONSTRAINT "individual_feature_individual_id_fkey" FOREIGN KEY (individual_id) REFERENCES individual(id) ON UPDATE CASCADE ON DELETE CASCADE
    TABLE "individual_gene" CONSTRAINT "individual_gene_individual_id_fkey" FOREIGN KEY (individual_id) REFERENCES individual(id) ON UPDATE CASCADE ON DELETE CASCADE
Triggers:
    individual_phenopolis_id_update BEFORE INSERT OR UPDATE ON individual FOR EACH ROW EXECUTE FUNCTION individual_phenopolis_id_update()
```
