### ISSUE TITLE
Error in local deployed Login API

### ISSUE THREAD

**Issue by YuanTian1991** [phenopolis/phenopolis_browser#193]
The bug performance is: Any password or user name could trigger “login success”, but actually none of them could actually be logged in. However, the online dev API seems fine.

So based on my current test, I guess the reason is the user table added one more column (enable?), but the demo database local version seems not included this modification? 

Below seems to be the line that triggered the bug. I guess this function (`check_auth`) was supposed to return “TRUE” or “FALSE”, but in my test, it seems returned an error. I don’t know why subsequently the login API returned status 200, but with some error information.

https://github.com/phenopolis/phenopolis_api/blob/b6d0f5f55bf1529f432627524507abad55f4d778/views/auth.py#L26

---

Personally I think:

1. I am not sure if I set up everything correctly, but I had run `docker rm phenopolis_api_app_1 phenopolis_api_db_1` before I start the docker. If it's my setting up issue, please close this issue.

2. If it's indeed a bug, triggered by unmodified demo database, a quick fix might be adding modify into the db, or add error judgement for `check_auth()` function

3. I think a bit dangerous that if any error happens in API function (failed), it will return 200. Maybe a better implementation is to make error situation return 500. However, I am not a backend (or python) expert, so not sure if it's possible or a reasonable design.

**Comment by pontikos** [comment]
@YuanTian1991 is this fixed?

**Comment by alanwilter** [comment]
Yep, this is fixed:
```bash
curl -c cookies.txt --header "Content-Type: application/json" \
  --request POST \
  --data '{"user": "demo","password": "hello"}' \
  http://localhost:8888/api/login

{"error":"Invalid Credentials. Please try again."}
```

The concerning code has changed to:
```python
def check_auth(username, password):
    """
    This function is called to check if a username / password combination is valid.
    """
    with session_scope() as db_session:
        # only enabled and confirmed users can login
        user = db_session.query(User).filter(and_(User.user == username, User.enabled, User.confirmed)).first()
        if not user:
            return False
        hashed_password = user.argon_password
    return argon2.verify(password, hashed_password)
```
