### ISSUE TITLE
missing `Create Patient` button on `my_patients` page

### ISSUE THREAD

**Issue by logust79** [phenopolis/phenopolis_browser#303]
Would be good to have a button or link to the `create_patient` page on the `my_patients` page.

**Comment by pontikos** [comment]
@YuanTian1991 can you implement this please and close issue?

**Comment by pontikos** [comment]
@alanwilter @YuanTian1991 I understand there has been some issues fixing this that you have discussed on Slack.  Can you please provide a succint update here on what the issues are so we are all on the same page?

**Comment by alanwilter** [comment]
I need to sort #352 and #169 first for @YuanTian1991. I'm working on genes now.

**Comment by alanwilter** [comment]
To summarise:
1. Create a delete_user endpoint;
2. Create an endpoint to return all Genes for a given user;
3. Create an endpoint to return all HPOs for a given user;
4. Create an endpoint to return all Variants for a given user.

However, I need to check which conflicts these actions may have with refactoring of the code for migrating to new schema. I won't invest time creating endpoints that may still use the old schema.

**Comment by pontikos** [comment]
see #242

**Comment by pontikos** [comment]
@YuanTian1991 for demo you need to handle `405 {"error":"Demo user not authorised"}` message

**Comment by YuanTian1991** [comment]
Fixed this bug.

**Comment by alanwilter** [comment]
Should we close it then?

**Comment by alanwilter** [comment]
Sorry, I think I found a problem, demo sees the button `Create New Patient` in http://localhost:8888/create_patient I guess it shouldn't.
